$(document).ready(function(){
  $(".design").click(function(){
    $(".design_hide").toggle();
    $(".design_show").toggle();
  });
});
$(document).ready(function(){
  $(".dev").click(function(){
    $(".dev_hide").toggle();
    $(".dev_show").toggle();
  });
});
$(document).ready(function(){
  $(".product").click(function(){
    $(".product_hide").toggle();
    $(".product_show").toggle();
  });
});
